// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI1ZBm4utYhOVjRjL1BSnoD1s_wUuEWrU',
    appId: '1:204394608709:android:d084d949d45b0054144b2c',
    messagingSenderId: '204394608709',
    projectId: 'quiz-app-sanika',
    storageBucket: 'quiz-app-sanika.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjbjxncYEW0pMkPN7BTqExbbH6RxIu8rY',
    appId: '1:204394608709:ios:52d3a7fa2b69bd75144b2c',
    messagingSenderId: '204394608709',
    projectId: 'quiz-app-sanika',
    storageBucket: 'quiz-app-sanika.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0G7odxczpP7idkJAdrh6AfwmqYwDqk30',
    appId: '1:204394608709:web:f347ee02c7fd4d3d144b2c',
    messagingSenderId: '204394608709',
    projectId: 'quiz-app-sanika',
    authDomain: 'quiz-app-sanika.firebaseapp.com',
    storageBucket: 'quiz-app-sanika.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjbjxncYEW0pMkPN7BTqExbbH6RxIu8rY',
    appId: '1:204394608709:ios:52d3a7fa2b69bd75144b2c',
    messagingSenderId: '204394608709',
    projectId: 'quiz-app-sanika',
    storageBucket: 'quiz-app-sanika.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0G7odxczpP7idkJAdrh6AfwmqYwDqk30',
    appId: '1:204394608709:web:6be7101a973a1eb0144b2c',
    messagingSenderId: '204394608709',
    projectId: 'quiz-app-sanika',
    authDomain: 'quiz-app-sanika.firebaseapp.com',
    storageBucket: 'quiz-app-sanika.firebasestorage.app',
  );

}